<a href="https://colab.research.google.com/github/aryanchaprana/aryanchaprana/blob/main/ML_5(Encoding_Categorical_data).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### ***ORDINAL ENCODING***

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
df=pd.read_csv('/content/customer.csv')

In [3]:
df.sample(6)

age  gender   review education purchased
12   51    Male     Poor    School        No
40   39    Male     Good    School        No
3    72  Female     Good        PG        No
20   57  Female  Average    School       Yes
29   83  Female  Average        UG       Yes
8    65  Female  Average        UG        No

In [4]:
df=df.iloc[:,2:]

In [5]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [6]:
from sklearn.model_selection import train_test_split
X=df.iloc[:, :-1]
y=df.iloc[:,-1]


In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [8]:
from sklearn.preprocessing import OrdinalEncoder

oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])


In [9]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [10]:
X_train=oe.transform(X_train)
X_test=oe.transform(X_test)


### ***LABEL ENCODER***

In [11]:
from sklearn.preprocessing import LabelEncoder #We should use label encoding only on the output data not the input data
le=LabelEncoder()
le.fit(y_train)
y_train=le.transform(y_train)
y_test=le.transform(y_test)


In [12]:
y_train

array([0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0])

### ***ONE HOT ENCODER(NOMINAL)***

In [13]:
dff=pd.read_csv('/content/cars.csv')
print(dff['brand'].nunique())# it tells how many types of brand are there
print(dff.head())
#dff['brand'].value_counts()



32
     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000


In [14]:
X=dff.iloc[:,0:4]
y=dff.iloc[:,-1]

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [37]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(drop='first',dtype=np.int32)
X_trainn=ohe.fit_transform(X_train[['fuel','owner']]).toarray() #converts it to array
X_testt=ohe.transform(X_test[['fuel','owner']]).toarray()




In [38]:
print(X_trainn)

[[0 0 1 ... 0 0 0]
 [0 0 1 ... 1 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 1 ... 1 0 0]]


In [39]:
np.hstack((X_train[['brand','km_driven']].values,X_trainn))

array([['Tata', 2560, 0, ..., 0, 0, 0],
       ['Honda', 80000, 0, ..., 1, 0, 0],
       ['Hyundai', 150000, 1, ..., 0, 0, 0],
       ...,
       ['Hyundai', 35000, 0, ..., 0, 0, 0],
       ['Maruti', 27000, 1, ..., 0, 0, 0],
       ['Maruti', 70000, 0, ..., 1, 0, 0]], dtype=object)

In [42]:
np.hstack((X_train[['brand','km_driven']].values,X_trainn)).shape

(6502, 9)

### ***ONE HOT ENCODING IN TOO MANY CATEGORIES***

In [45]:
counts=dff['brand'].value_counts()


In [47]:
dff['brand'].nunique()
threshold= 100 #this is like the values which are less than 100 will be converted to others

In [49]:
replace=counts[counts <= threshold].index  #this tells us which are the values less than 100

In [50]:
pd.get_dummies(dff['brand'].replace(replace,'others'))

BMW  Chevrolet   Ford  Honda  Hyundai  Mahindra  Maruti  Renault  \
0     False      False  False  False    False     False    True    False   
1     False      False  False  False    False     False   False    False   
2     False      False  False   True    False     False   False    False   
3     False      False  False  False     True     False   False    False   
4     False      False  False  False    False     False    True    False   
...     ...        ...    ...    ...      ...       ...     ...      ...   
8123  False      False  False  False     True     False   False    False   
8124  False      False  False  False     True     False   False    False   
8125  False      False  False  False    False     False    True    False   
8126  False      False  False  False    False     False   False    False   
8127  False      False  False  False    False     False   False    False   

      Skoda   Tata  Toyota  Volkswagen  others  
0     False  False   False       False   False  
1      True  False   False       False   False  
2     False  False   False       False   False  
3     False  False   False       False   False  
4     False  False   False       False   False  
...     ...    ...     ...         ...     ...  
8123  False  False   False       False   False  
8124  False  False   False       False   False  
8125  False  False   False       False   False  
8126  False   True   False       False   False  
8127  False   True   False       False   False  

[8128 rows x 13 columns]